---
title: Maak een grafische gebruikersinterface voor verkeerslichten
hero_image: images / banner.png
description: Creëer een GUI voor verkeerslichten (grafische gebruikersinterface) met GPIO Zero en guizero.
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "fysiek computergebruik"
technologies: "elektronica, fysieke computergebruik, python"
site_areas: ""
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Flits de leds
  - 
    title: Maak een GUI
  - 
    title: Uitdagingen
