---
title: Maak een grafische interface voor een verkeerslichtcontroller
hero_image: images/banner.png
description: Maak een verkeerslicht controller GUI (grafische gebruikersinterface) met Python
listed: false
copyedit: false
version: 4
last_tested: 2018-11-21
steps:
  - 
    title: Inleiding
  - 
    title: Laat de LED's knopperen
  - 
    title: Maak een GUI
  - 
    title: Uitdagingen
