title: Make a Traffic Lights Controller GUI
hero_image: images/banner.png
description: Create a traffic lights controller GUI (graphical user interface) using GPIO Zero and guizero.
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Flash the LEDs
  - title: Create a GUI
  - title: Challenges
