---
title: Traffic Lights Controller GUI
hero_image: images/banner.png
description: Create a traffic lights controller GUI (graphical user interface) using Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: भूमिका
  - 
    title: एल. ई. डी. को जलाये
  - 
    title: एक GUI बनाएँ
  - 
    title: चुनौतियाँ
