---
title: トラフィックライトコントローラのGUIを作成する
hero_image: images / banner.png
description: GPIO Zeroとguizeroを使用して、信号機コントローラGUI（グラフィカルユーザインタフェース）を作成します。
theme: 赤
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: プログラミング-0、phys-comp-0
interests: "物理計算"
technologies: "エレクトロニクス、物理計算機、Python"
site_areas: ""
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: LEDをフラッシュする
  - 
    title: GUIの作成
  - 
    title: 課題
