---
title: Направете GUI контролер за осветление на трафика
hero_image: изображения / banner.png
description: Създайте GUI контролер (графичен потребителски интерфейс), като използвате GPIO Zero и guizero.
theme: червен
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: програмиране-0, phys-comp-0
interests: "физически изчисления"
technologies: "електроника, физически изчисления, питон"
site_areas: ""
steps:
  - 
    title: Въведение
  - 
    title: Какво ще ви трябва
  - 
    title: Светли светодиоди
  - 
    title: Създайте GUI
  - 
    title: предизвикателства
