---
title: رابط کاربر گرافیکی برای کنترل چراغ راهنمایی
hero_image: images/banner.png
description: ایجاد یک GUI (رابط گرافیکی کاربر) برای کنترل چراغ راهنمایی با استفاده از پایتون
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: مقدمه
  - 
    title: LEDها را خاموش و روشن کنید
  - 
    title: ایجاد یک رابط کاربری گرافیکی
  - 
    title: چالش ها
