---
title: Erstellen Sie eine Ampel-Controller-GUI
hero_image: Bilder / Banner.png
description: Erstellen Sie eine Ampel-Controller-GUI (grafische Benutzeroberfläche) mit GPIO Zero und Guizero.
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Elektronik, physikalisches Rechnen, Python"
site_areas: ""
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Blinken Sie die LEDs
  - 
    title: Erstellen Sie eine GUI
  - 
    title: Herausforderungen
