---
title: Contrôleur de feux de circulation
hero_image: images/banner.png
description: Créer une interface de contrôleur de feux de circulation GUI (interface utilisateur graphique) en utilisant Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Fais clignoter les LED
  - 
    title: Créer une interface graphique
  - 
    title: Défis
